// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sample_alpha_cpp
NumericVector sample_alpha_cpp(NumericVector eta_zct_flat, NumericMatrix Dc_mat, NumericVector a2_z, NumericVector b2_z, NumericVector mz0_vec, NumericMatrix Sz0_mat, int n_topic, int n_time, int n_cust, int p_dim);
RcppExport SEXP _MRDLTM_sample_alpha_cpp(SEXP eta_zct_flatSEXP, SEXP Dc_matSEXP, SEXP a2_zSEXP, SEXP b2_zSEXP, SEXP mz0_vecSEXP, SEXP Sz0_matSEXP, SEXP n_topicSEXP, SEXP n_timeSEXP, SEXP n_custSEXP, SEXP p_dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type eta_zct_flat(eta_zct_flatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Dc_mat(Dc_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a2_z(a2_zSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b2_z(b2_zSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mz0_vec(mz0_vecSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Sz0_mat(Sz0_matSEXP);
    Rcpp::traits::input_parameter< int >::type n_topic(n_topicSEXP);
    Rcpp::traits::input_parameter< int >::type n_time(n_timeSEXP);
    Rcpp::traits::input_parameter< int >::type n_cust(n_custSEXP);
    Rcpp::traits::input_parameter< int >::type p_dim(p_dimSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_alpha_cpp(eta_zct_flat, Dc_mat, a2_z, b2_z, mz0_vec, Sz0_mat, n_topic, n_time, n_cust, p_dim));
    return rcpp_result_gen;
END_RCPP
}
// sample_beta_cpp
NumericVector sample_beta_cpp(IntegerVector z_cit, IntegerVector item_idx, IntegerVector time_idx, NumericVector u_cit, NumericVector x_it_flat, NumericMatrix mu_i_mat, NumericVector V_i_flat, int n_topic, int n_item, int n_time, int n_var);
RcppExport SEXP _MRDLTM_sample_beta_cpp(SEXP z_citSEXP, SEXP item_idxSEXP, SEXP time_idxSEXP, SEXP u_citSEXP, SEXP x_it_flatSEXP, SEXP mu_i_matSEXP, SEXP V_i_flatSEXP, SEXP n_topicSEXP, SEXP n_itemSEXP, SEXP n_timeSEXP, SEXP n_varSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type z_cit(z_citSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type item_idx(item_idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type time_idx(time_idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type u_cit(u_citSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_it_flat(x_it_flatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mu_i_mat(mu_i_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type V_i_flat(V_i_flatSEXP);
    Rcpp::traits::input_parameter< int >::type n_topic(n_topicSEXP);
    Rcpp::traits::input_parameter< int >::type n_item(n_itemSEXP);
    Rcpp::traits::input_parameter< int >::type n_time(n_timeSEXP);
    Rcpp::traits::input_parameter< int >::type n_var(n_varSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_beta_cpp(z_cit, item_idx, time_idx, u_cit, x_it_flat, mu_i_mat, V_i_flat, n_topic, n_item, n_time, n_var));
    return rcpp_result_gen;
END_RCPP
}
// sample_dlm_vars_cpp
List sample_dlm_vars_cpp(NumericVector eta_zct_flat, NumericVector alpha_zt_flat, NumericMatrix Dc_mat, double a2_prior_shape, double a2_prior_scale, double b2_prior_shape, double b2_prior_scale, int n_topic, int n_time, int n_cust, int p_dim);
RcppExport SEXP _MRDLTM_sample_dlm_vars_cpp(SEXP eta_zct_flatSEXP, SEXP alpha_zt_flatSEXP, SEXP Dc_matSEXP, SEXP a2_prior_shapeSEXP, SEXP a2_prior_scaleSEXP, SEXP b2_prior_shapeSEXP, SEXP b2_prior_scaleSEXP, SEXP n_topicSEXP, SEXP n_timeSEXP, SEXP n_custSEXP, SEXP p_dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type eta_zct_flat(eta_zct_flatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha_zt_flat(alpha_zt_flatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Dc_mat(Dc_matSEXP);
    Rcpp::traits::input_parameter< double >::type a2_prior_shape(a2_prior_shapeSEXP);
    Rcpp::traits::input_parameter< double >::type a2_prior_scale(a2_prior_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type b2_prior_shape(b2_prior_shapeSEXP);
    Rcpp::traits::input_parameter< double >::type b2_prior_scale(b2_prior_scaleSEXP);
    Rcpp::traits::input_parameter< int >::type n_topic(n_topicSEXP);
    Rcpp::traits::input_parameter< int >::type n_time(n_timeSEXP);
    Rcpp::traits::input_parameter< int >::type n_cust(n_custSEXP);
    Rcpp::traits::input_parameter< int >::type p_dim(p_dimSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_dlm_vars_cpp(eta_zct_flat, alpha_zt_flat, Dc_mat, a2_prior_shape, a2_prior_scale, b2_prior_shape, b2_prior_scale, n_topic, n_time, n_cust, p_dim));
    return rcpp_result_gen;
END_RCPP
}
// sample_eta_prepare_cpp
List sample_eta_prepare_cpp(IntegerVector z_cit_flat, IntegerVector obs_cust, IntegerVector obs_time, NumericVector eta_zct_flat, int n_topic, int n_time, int n_cust);
RcppExport SEXP _MRDLTM_sample_eta_prepare_cpp(SEXP z_cit_flatSEXP, SEXP obs_custSEXP, SEXP obs_timeSEXP, SEXP eta_zct_flatSEXP, SEXP n_topicSEXP, SEXP n_timeSEXP, SEXP n_custSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type z_cit_flat(z_cit_flatSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type obs_cust(obs_custSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type obs_time(obs_timeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type eta_zct_flat(eta_zct_flatSEXP);
    Rcpp::traits::input_parameter< int >::type n_topic(n_topicSEXP);
    Rcpp::traits::input_parameter< int >::type n_time(n_timeSEXP);
    Rcpp::traits::input_parameter< int >::type n_cust(n_custSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_eta_prepare_cpp(z_cit_flat, obs_cust, obs_time, eta_zct_flat, n_topic, n_time, n_cust));
    return rcpp_result_gen;
END_RCPP
}
// sample_eta_update_cpp
NumericVector sample_eta_update_cpp(NumericVector eta_zct_flat, NumericVector omega_vec, NumericVector log_C_vec, NumericVector n_kct_vec, NumericVector N_ct_vec, NumericVector alpha_zt_flat, NumericMatrix Dc_mat, arma::vec a2_z, int n_topic, int n_time, int n_cust, int p_dim);
RcppExport SEXP _MRDLTM_sample_eta_update_cpp(SEXP eta_zct_flatSEXP, SEXP omega_vecSEXP, SEXP log_C_vecSEXP, SEXP n_kct_vecSEXP, SEXP N_ct_vecSEXP, SEXP alpha_zt_flatSEXP, SEXP Dc_matSEXP, SEXP a2_zSEXP, SEXP n_topicSEXP, SEXP n_timeSEXP, SEXP n_custSEXP, SEXP p_dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type eta_zct_flat(eta_zct_flatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type omega_vec(omega_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type log_C_vec(log_C_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n_kct_vec(n_kct_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type N_ct_vec(N_ct_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha_zt_flat(alpha_zt_flatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Dc_mat(Dc_matSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type a2_z(a2_zSEXP);
    Rcpp::traits::input_parameter< int >::type n_topic(n_topicSEXP);
    Rcpp::traits::input_parameter< int >::type n_time(n_timeSEXP);
    Rcpp::traits::input_parameter< int >::type n_cust(n_custSEXP);
    Rcpp::traits::input_parameter< int >::type p_dim(p_dimSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_eta_update_cpp(eta_zct_flat, omega_vec, log_C_vec, n_kct_vec, N_ct_vec, alpha_zt_flat, Dc_mat, a2_z, n_topic, n_time, n_cust, p_dim));
    return rcpp_result_gen;
END_RCPP
}
// sample_mu_V_cpp
List sample_mu_V_cpp(NumericVector beta_zi_flat, NumericMatrix mu_i_mat, NumericVector V_i_flat, arma::vec mu_tilde, double sigma_tilde_mu, double w_tilde, arma::mat W_tilde, int n_topic, int n_item, int n_var);
RcppExport SEXP _MRDLTM_sample_mu_V_cpp(SEXP beta_zi_flatSEXP, SEXP mu_i_matSEXP, SEXP V_i_flatSEXP, SEXP mu_tildeSEXP, SEXP sigma_tilde_muSEXP, SEXP w_tildeSEXP, SEXP W_tildeSEXP, SEXP n_topicSEXP, SEXP n_itemSEXP, SEXP n_varSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type beta_zi_flat(beta_zi_flatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mu_i_mat(mu_i_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type V_i_flat(V_i_flatSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu_tilde(mu_tildeSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_tilde_mu(sigma_tilde_muSEXP);
    Rcpp::traits::input_parameter< double >::type w_tilde(w_tildeSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W_tilde(W_tildeSEXP);
    Rcpp::traits::input_parameter< int >::type n_topic(n_topicSEXP);
    Rcpp::traits::input_parameter< int >::type n_item(n_itemSEXP);
    Rcpp::traits::input_parameter< int >::type n_var(n_varSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_mu_V_cpp(beta_zi_flat, mu_i_mat, V_i_flat, mu_tilde, sigma_tilde_mu, w_tilde, W_tilde, n_topic, n_item, n_var));
    return rcpp_result_gen;
END_RCPP
}
// sample_u_cpp
NumericVector sample_u_cpp(IntegerVector y_cit, NumericMatrix x_it_matrix, NumericVector beta_zi_flat, IntegerVector z_cit, IntegerVector item_idx, IntegerVector time_idx, int n_topic, int n_item, int n_var);
RcppExport SEXP _MRDLTM_sample_u_cpp(SEXP y_citSEXP, SEXP x_it_matrixSEXP, SEXP beta_zi_flatSEXP, SEXP z_citSEXP, SEXP item_idxSEXP, SEXP time_idxSEXP, SEXP n_topicSEXP, SEXP n_itemSEXP, SEXP n_varSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type y_cit(y_citSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x_it_matrix(x_it_matrixSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta_zi_flat(beta_zi_flatSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type z_cit(z_citSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type item_idx(item_idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type time_idx(time_idxSEXP);
    Rcpp::traits::input_parameter< int >::type n_topic(n_topicSEXP);
    Rcpp::traits::input_parameter< int >::type n_item(n_itemSEXP);
    Rcpp::traits::input_parameter< int >::type n_var(n_varSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_u_cpp(y_cit, x_it_matrix, beta_zi_flat, z_cit, item_idx, time_idx, n_topic, n_item, n_var));
    return rcpp_result_gen;
END_RCPP
}
// sample_z_cpp
IntegerVector sample_z_cpp(NumericVector u_cit, NumericVector eta_flat, NumericVector beta_flat, NumericVector x_flat, IntegerVector cust_idx, IntegerVector item_idx, IntegerVector time_idx, NumericVector rand_u, int n_topic, int n_item, int n_time, int n_cust, int n_var);
RcppExport SEXP _MRDLTM_sample_z_cpp(SEXP u_citSEXP, SEXP eta_flatSEXP, SEXP beta_flatSEXP, SEXP x_flatSEXP, SEXP cust_idxSEXP, SEXP item_idxSEXP, SEXP time_idxSEXP, SEXP rand_uSEXP, SEXP n_topicSEXP, SEXP n_itemSEXP, SEXP n_timeSEXP, SEXP n_custSEXP, SEXP n_varSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type u_cit(u_citSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type eta_flat(eta_flatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta_flat(beta_flatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_flat(x_flatSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cust_idx(cust_idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type item_idx(item_idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type time_idx(time_idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rand_u(rand_uSEXP);
    Rcpp::traits::input_parameter< int >::type n_topic(n_topicSEXP);
    Rcpp::traits::input_parameter< int >::type n_item(n_itemSEXP);
    Rcpp::traits::input_parameter< int >::type n_time(n_timeSEXP);
    Rcpp::traits::input_parameter< int >::type n_cust(n_custSEXP);
    Rcpp::traits::input_parameter< int >::type n_var(n_varSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_z_cpp(u_cit, eta_flat, beta_flat, x_flat, cust_idx, item_idx, time_idx, rand_u, n_topic, n_item, n_time, n_cust, n_var));
    return rcpp_result_gen;
END_RCPP
}
// compute_log_likelihood_cpp
double compute_log_likelihood_cpp(IntegerVector z_cit, IntegerVector item_idx, IntegerVector time_idx, IntegerVector y_cit, NumericVector beta_zi_flat, NumericVector x_it_flat, int n_topic, int n_item, int n_time, int n_var);
RcppExport SEXP _MRDLTM_compute_log_likelihood_cpp(SEXP z_citSEXP, SEXP item_idxSEXP, SEXP time_idxSEXP, SEXP y_citSEXP, SEXP beta_zi_flatSEXP, SEXP x_it_flatSEXP, SEXP n_topicSEXP, SEXP n_itemSEXP, SEXP n_timeSEXP, SEXP n_varSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type z_cit(z_citSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type item_idx(item_idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type time_idx(time_idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y_cit(y_citSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta_zi_flat(beta_zi_flatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_it_flat(x_it_flatSEXP);
    Rcpp::traits::input_parameter< int >::type n_topic(n_topicSEXP);
    Rcpp::traits::input_parameter< int >::type n_item(n_itemSEXP);
    Rcpp::traits::input_parameter< int >::type n_time(n_timeSEXP);
    Rcpp::traits::input_parameter< int >::type n_var(n_varSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_log_likelihood_cpp(z_cit, item_idx, time_idx, y_cit, beta_zi_flat, x_it_flat, n_topic, n_item, n_time, n_var));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MRDLTM_sample_alpha_cpp", (DL_FUNC) &_MRDLTM_sample_alpha_cpp, 10},
    {"_MRDLTM_sample_beta_cpp", (DL_FUNC) &_MRDLTM_sample_beta_cpp, 11},
    {"_MRDLTM_sample_dlm_vars_cpp", (DL_FUNC) &_MRDLTM_sample_dlm_vars_cpp, 11},
    {"_MRDLTM_sample_eta_prepare_cpp", (DL_FUNC) &_MRDLTM_sample_eta_prepare_cpp, 7},
    {"_MRDLTM_sample_eta_update_cpp", (DL_FUNC) &_MRDLTM_sample_eta_update_cpp, 12},
    {"_MRDLTM_sample_mu_V_cpp", (DL_FUNC) &_MRDLTM_sample_mu_V_cpp, 10},
    {"_MRDLTM_sample_u_cpp", (DL_FUNC) &_MRDLTM_sample_u_cpp, 9},
    {"_MRDLTM_sample_z_cpp", (DL_FUNC) &_MRDLTM_sample_z_cpp, 13},
    {"_MRDLTM_compute_log_likelihood_cpp", (DL_FUNC) &_MRDLTM_compute_log_likelihood_cpp, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_MRDLTM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
