# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_alpha_cpp <- function(eta_zct_flat, Dc_mat, a2_z, b2_z, mz0_vec, Sz0_mat, n_topic, n_time, n_cust, p_dim) {
    .Call(`_MRDLTM_sample_alpha_cpp`, eta_zct_flat, Dc_mat, a2_z, b2_z, mz0_vec, Sz0_mat, n_topic, n_time, n_cust, p_dim)
}

sample_beta_cpp <- function(z_cit, item_idx, time_idx, u_cit, x_it_flat, mu_i_mat, V_i_flat, n_topic, n_item, n_time, n_var) {
    .Call(`_MRDLTM_sample_beta_cpp`, z_cit, item_idx, time_idx, u_cit, x_it_flat, mu_i_mat, V_i_flat, n_topic, n_item, n_time, n_var)
}

sample_dlm_vars_cpp <- function(eta_zct_flat, alpha_zt_flat, Dc_mat, a2_prior_shape, a2_prior_scale, b2_prior_shape, b2_prior_scale, n_topic, n_time, n_cust, p_dim) {
    .Call(`_MRDLTM_sample_dlm_vars_cpp`, eta_zct_flat, alpha_zt_flat, Dc_mat, a2_prior_shape, a2_prior_scale, b2_prior_shape, b2_prior_scale, n_topic, n_time, n_cust, p_dim)
}

sample_eta_prepare_cpp <- function(z_cit_flat, obs_cust, obs_time, eta_zct_flat, n_topic, n_time, n_cust) {
    .Call(`_MRDLTM_sample_eta_prepare_cpp`, z_cit_flat, obs_cust, obs_time, eta_zct_flat, n_topic, n_time, n_cust)
}

sample_eta_update_cpp <- function(eta_zct_flat, omega_vec, log_C_vec, n_kct_vec, N_ct_vec, alpha_zt_flat, Dc_mat, a2_z, n_topic, n_time, n_cust, p_dim) {
    .Call(`_MRDLTM_sample_eta_update_cpp`, eta_zct_flat, omega_vec, log_C_vec, n_kct_vec, N_ct_vec, alpha_zt_flat, Dc_mat, a2_z, n_topic, n_time, n_cust, p_dim)
}

sample_mu_V_cpp <- function(beta_zi_flat, mu_i_mat, V_i_flat, mu_tilde, sigma_tilde_mu, w_tilde, W_tilde, n_topic, n_item, n_var) {
    .Call(`_MRDLTM_sample_mu_V_cpp`, beta_zi_flat, mu_i_mat, V_i_flat, mu_tilde, sigma_tilde_mu, w_tilde, W_tilde, n_topic, n_item, n_var)
}

sample_u_cpp <- function(y_cit, x_it_matrix, beta_zi_flat, z_cit, item_idx, time_idx, n_topic, n_item, n_var) {
    .Call(`_MRDLTM_sample_u_cpp`, y_cit, x_it_matrix, beta_zi_flat, z_cit, item_idx, time_idx, n_topic, n_item, n_var)
}

sample_z_cpp <- function(u_cit, eta_flat, beta_flat, x_flat, cust_idx, item_idx, time_idx, rand_u, n_topic, n_item, n_time, n_cust, n_var) {
    .Call(`_MRDLTM_sample_z_cpp`, u_cit, eta_flat, beta_flat, x_flat, cust_idx, item_idx, time_idx, rand_u, n_topic, n_item, n_time, n_cust, n_var)
}

compute_log_likelihood_cpp <- function(z_cit, item_idx, time_idx, y_cit, beta_zi_flat, x_it_flat, n_topic, n_item, n_time, n_var) {
    .Call(`_MRDLTM_compute_log_likelihood_cpp`, z_cit, item_idx, time_idx, y_cit, beta_zi_flat, x_it_flat, n_topic, n_item, n_time, n_var)
}

