# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_beta_cpp <- function(u_cit, x_it_matrix, z_cit, item_idx, time_idx, mu_beta_zi, V_inv_zi, n_topic, n_item, n_var) {
    .Call(`_MRDLTM_sample_beta_cpp`, u_cit, x_it_matrix, z_cit, item_idx, time_idx, mu_beta_zi, V_inv_zi, n_topic, n_item, n_var)
}

sample_u_cpp <- function(y_cit, x_it_matrix, beta_zi_flat, z_cit, item_idx, time_idx, n_topic, n_item, n_var) {
    .Call(`_MRDLTM_sample_u_cpp`, y_cit, x_it_matrix, beta_zi_flat, z_cit, item_idx, time_idx, n_topic, n_item, n_var)
}

sample_z_cpp <- function(u_cit, eta_zct_flat, beta_zi_flat, x_it_matrix, cust_idx, item_idx, time_idx, n_topic, n_item, n_cust, n_var) {
    .Call(`_MRDLTM_sample_z_cpp`, u_cit, eta_zct_flat, beta_zi_flat, x_it_matrix, cust_idx, item_idx, time_idx, n_topic, n_item, n_cust, n_var)
}

