# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_z_cpp <- function(u_cit, prob_matrix_flat, n_topic) {
    .Call(`_MRDLTM_sample_z_cpp`, u_cit, prob_matrix_flat, n_topic)
}

